"""
Transport falsification suite for the fixed MPRC digit benchmark.

Reproduces:
1. exact QH4 mixed-radix active map (252 states, four vacua);
2. exact local T_k involution gates;
3. six-element group generated by the three T_k reflections;
4. D3 orbit canonicalization / transport augmentation ablations;
5. generator-7 phase-invariant [1,2,4] histogram ablations.

The image task is intentionally still the 8x8 digit diagnostic. It is NOT a
claim of native Arshad-ViT byte topology; the native 32x32 CIFAR transport
experiment lives in scripts/cifar10_native32.py.
"""

from pathlib import Path
from collections import Counter
import json
import numpy as np
from PIL import Image, ImageFilter
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split

ROOT = Path(__file__).resolve().parents[1]
DATA = np.load(ROOT / "data" / "digits_seed42.npz")
X = DATA["X"].astype(np.uint8).reshape(-1, 8, 8)
y = DATA["y"].astype(np.int64)

idx = np.arange(len(y))
train_idx, test_idx = train_test_split(
    idx, test_size=0.30, random_state=42, stratify=y
)
fit_idx, val_idx = train_test_split(
    train_idx, test_size=0.20, random_state=314, stratify=y[train_idx]
)

U8 = ((X.astype(np.uint16) * 255) // 16).astype(np.uint8)


def blur(a, r):
    return np.array(
        Image.fromarray(a, "L").filter(ImageFilter.BoxBlur(r)),
        dtype=np.uint8,
    )


def adiff(a, b):
    return np.abs(a.astype(np.int16) - b.astype(np.int16)).astype(np.uint8)


def channels(img):
    l = img.astype(np.uint8)
    gx = np.zeros_like(l, dtype=np.int16)
    gy = np.zeros_like(l, dtype=np.int16)
    gx[:, 1:-1] = l[:, 2:].astype(np.int16) - l[:, :-2].astype(np.int16)
    gy[1:-1, :] = l[2:, :].astype(np.int16) - l[:-2, :].astype(np.int16)

    b1, b2, b4, _ = [blur(l, r) for r in (1, 2, 4, 8)]

    return {
        "gy": np.clip(128 + gy // 2, 0, 255).astype(np.uint8),
        "grad": np.clip((np.abs(gx) + np.abs(gy)) // 2, 0, 255).astype(np.uint8),
        "h2": adiff(b1, b2),
        "m4": adiff(b2, b4),
    }


SELECTED = ["gy", "grad", "h2", "m4"]
CHANNELS = [channels(im) for im in U8]

orbit7 = []
q = 0
for _ in range(64):
    orbit7.append(q)
    q = (q + 7) & 63
assert len(set(orbit7)) == 64

EDGES = []
for r in range(8):
    for c in range(7):
        EDGES.append((r * 8 + c, r * 8 + c + 1))
for r in range(7):
    for c in range(8):
        EDGES.append((r * 8 + c, (r + 1) * 8 + c))
for r in range(7):
    for c in range(7):
        EDGES.append((r * 8 + c, (r + 1) * 8 + c + 1))
        EDGES.append((r * 8 + c + 1, (r + 1) * 8 + c))
for i in range(64):
    EDGES.append((orbit7[i], orbit7[(i + 1) % 64]))
assert len(EDGES) == 274


def qpair(img):
    f = img.reshape(-1)
    return np.asarray(
        [((int(f[i]) >> 6) << 2) | (int(f[j]) >> 6) for i, j in EDGES],
        dtype=np.uint8,
    )


K = 10
ALPHA = 0.05


class LUT:
    def fit(self, A, yy):
        counts = np.zeros((A.shape[1], K, 16), dtype=np.int32)
        for cls in range(K):
            rows = A[yy == cls]
            for j in range(A.shape[1]):
                counts[j, cls] = np.bincount(rows[:, j], minlength=16)
        total = counts.sum(axis=1, keepdims=True)
        self.table = np.log((counts + ALPHA) / (total + K * ALPHA))
        return self

    def fit_multi(self, arrays, yy):
        counts = np.zeros((arrays[0].shape[1], K, 16), dtype=np.int64)
        for A in arrays:
            for cls in range(K):
                rows = A[yy == cls]
                for j in range(A.shape[1]):
                    counts[j, cls] += np.bincount(rows[:, j], minlength=16)
        total = counts.sum(axis=1, keepdims=True)
        self.table = np.log((counts + ALPHA) / (total + K * ALPHA))
        return self

    def score(self, A):
        out = np.zeros((len(A), K), dtype=np.float64)
        for j in range(A.shape[1]):
            out += np.take(self.table[j], A[:, j], axis=1).T
        return out


def accuracy(scores, yy):
    return float(np.mean(scores.argmax(axis=1) == yy))


PRAW = {
    name: np.stack([qpair(c[name]) for c in CHANNELS])
    for name in SELECTED
}

# ------------------------------------------------------------------
# QH4 + T_k exact gates
# ------------------------------------------------------------------
VAC = {0, 64, 128, 192}
decode = {}
encode = {}

for gamma in range(1, 37):
    theta = (gamma - 1) // 9
    rem = (gamma - 1) % 9
    a = rem // 3
    p = rem % 3
    for sigma in range(1, 8):
        m = 64 * theta + 21 * a + 7 * p + sigma
        z = (7 * m) & 255
        assert z not in VAC
        decode[z] = (theta, a, p, sigma)
        encode[(theta, a, p, sigma)] = z

assert len(decode) == 252
assert set(range(256)) - set(decode) == VAC


def Tk(a, p, k):
    return ((p + k) % 3, (a - k) % 3)


def R(a, p, d):
    return ((a + d) % 3, (p - d) % 3)


for k in range(3):
    for _, (theta, a, p, sigma) in decode.items():
        a1, p1 = Tk(a, p, k)
        a2, p2 = Tk(a1, p1, k)
        assert (a2, p2) == (a, p)
        assert (a1 + p1) % 3 == (a + p) % 3
        j = (p - a) % 3
        assert (p1 - a1) % 3 == (-(j + 2 * k)) % 3

TRANSFORMS = []
for d in range(3):
    TRANSFORMS.append((f"R{d}", lambda a, p, d=d: R(a, p, d)))
for k in range(3):
    TRANSFORMS.append((f"T{k}", lambda a, p, k=k: Tk(a, p, k)))

byte_maps = {}
for name, fn in TRANSFORMS:
    arr = np.arange(256, dtype=np.uint8)
    for z, (theta, a, p, sigma) in decode.items():
        aa, pp = fn(a, p)
        arr[z] = encode[(theta, aa, pp, sigma)]
    byte_maps[name] = arr

canonical = np.arange(256, dtype=np.uint8)
orbit_sizes = []
for z in range(256):
    if z in VAC:
        continue
    orb = sorted({int(byte_maps[name][z]) for name, _ in TRANSFORMS})
    canonical[z] = orb[0]
    orbit_sizes.append(len(orb))

orbit_hist = Counter(orbit_sizes)
assert orbit_hist == {3: 252}
assert len({int(canonical[z]) for z in decode}) == 84

PCANON = {
    ch: np.stack([qpair(canonical[c[ch]]) for c in CHANNELS])
    for ch in SELECTED
}
PORBIT = {
    name: {
        ch: np.stack([qpair(byte_maps[name][c[ch]]) for c in CHANNELS])
        for ch in SELECTED
    }
    for name, _ in TRANSFORMS
}

VRAW = np.zeros((len(val_idx), K))
VCAN = np.zeros((len(val_idx), K))
VAUG = np.zeros((len(val_idx), K))
VORBIT = np.zeros((len(val_idx), K))

for ch in SELECTED:
    raw = LUT().fit(PRAW[ch][fit_idx], y[fit_idx])
    can = LUT().fit(PCANON[ch][fit_idx], y[fit_idx])
    aug = LUT().fit_multi(
        [PORBIT[name][ch][fit_idx] for name, _ in TRANSFORMS],
        y[fit_idx],
    )

    VRAW += raw.score(PRAW[ch][val_idx])
    VCAN += can.score(PCANON[ch][val_idx])
    VAUG += aug.score(PRAW[ch][val_idx])

    for name, _ in TRANSFORMS:
        VORBIT += aug.score(PORBIT[name][ch][val_idx])

transpose_validation = {
    "raw": accuracy(VRAW, y[val_idx]),
    "canonical": accuracy(VCAN, y[val_idx]),
    "augmented_raw_inference": accuracy(VAUG, y[val_idx]),
    "augmented_orbit_inference": accuracy(VORBIT, y[val_idx]),
}

# ------------------------------------------------------------------
# Generator-7 phase-invariant fingerprints
# ------------------------------------------------------------------
def pair_hist(seq, lag):
    h = np.zeros(16, dtype=np.uint8)
    for t in range(64):
        h[(seq[t] << 2) | seq[(t + lag) % 64]] += 1
    return h


def triple_hist(seq, l1, l2):
    h = np.zeros(64, dtype=np.uint8)
    for t in range(64):
        cat = (seq[t] << 4) | (seq[(t + l1) % 64] << 2) | seq[(t + l2) % 64]
        h[cat] += 1
    return h


def generator_fingerprint(img, mode):
    f = img.reshape(-1)
    seq = [int(f[i]) >> 6 for i in orbit7]

    if mode == "pair124":
        return np.concatenate([pair_hist(seq, lag) for lag in (1, 2, 4)])

    if mode == "triple124":
        return np.concatenate(
            [
                triple_hist(seq, 1, 2),
                triple_hist(seq, 1, 4),
                triple_hist(seq, 2, 4),
            ]
        )

    raise ValueError(mode)


generator_validation = {}
for mode in ("pair124", "triple124"):
    transport_score = np.zeros((len(val_idx), K))

    for ch in SELECTED:
        G = np.stack([generator_fingerprint(c[ch], mode) for c in CHANNELS])

        # Histogram counts are categorical values 0..64.
        maxstate = 65
        counts = np.zeros((G.shape[1], K, maxstate), dtype=np.int32)
        for cls in range(K):
            rows = G[fit_idx][y[fit_idx] == cls]
            for j in range(G.shape[1]):
                counts[j, cls] = np.bincount(rows[:, j], minlength=maxstate)

        total = counts.sum(axis=1, keepdims=True)
        table = np.log((counts + ALPHA) / (total + K * ALPHA))

        for j in range(G.shape[1]):
            transport_score += np.take(
                table[j],
                G[val_idx, j],
                axis=1,
            ).T

    generator_validation[mode] = accuracy(transport_score, y[val_idx])
    generator_validation["raw_plus_" + mode] = accuracy(
        VRAW + transport_score,
        y[val_idx],
    )

result = {
    "exact_gates": {
        "active_states": 252,
        "vacua": sorted(VAC),
        "D3_transform_count": 6,
        "active_orbit_histogram": dict(orbit_hist),
        "canonical_active_classes": 84,
    },
    "transpose_validation": transpose_validation,
    "generator_validation": generator_validation,
}

out = ROOT / "results" / "transport_falsification_digits.json"
out.write_text(json.dumps(result, indent=2), encoding="utf-8")
print(json.dumps(result, indent=2))